### ISSUE TITLE
Library is not pip-installable

### ISSUE THREAD

**Issue by rishsriv** [LokiTechnologies/EqualAreaCartogram#2]

**Comment by psychemedia** [comment]
With error:

```
Collecting git+https://github.com/LokiTechnologies/EqualAreaCartogram.git
  Cloning https://github.com/LokiTechnologies/EqualAreaCartogram.git to /tmp/pip-ep42jfke-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-????-build/setup.py'
```

**Comment by psychemedia** [comment]
I'm guessing at this (I've not really tried packaging much), but how about:

`setup.py`:

```
from setuptools import setup

setup(name='EqualAreaCartogram',
      version='0.1',
      description='Plot equal area cartograms',
      url='https://github.com/LokiTechnologies/EqualAreaCartogram',
      author='rishsriv, datavistics',
      license='MIT',
      packages=['eqcart', 'chorogrid'],
      install_requires=['beautifulsoup4','pandas','geopandas'],
      zip_safe=False)
```

Then directory structure:

```
-- eqcart
  -- __init__.py
  -- eqcart.py
-- chorogrid
  -- __init__.py
  -- chorogrid.py
```

then something like `from .eqcart import *` in first `__init__.py` and  `from .chorogrid import *` in second one?

**Comment by rishsriv** [comment]
Thanks! Would you like to create a pull request? If not, will try to do this in a couple of days.
